#!/bin/bash

# This script compiles lxc and creates a zipfile that can be shipped

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo "Setting up build environment..."
if [ -e "/tmp/lxcbuild" ]; then
	rm -fr "/tmp/lxcbuild"
fi
mkdir "/tmp/lxcbuild"
mkdir "/tmp/lxcbuild/classes"

echo "Copying files to build dir..."
cp -r * "/tmp/lxcbuild"

echo "Compiling..."
cd "/tmp/lxcbuild"
javac -encoding utf8 -d classes -sourcepath src -source 6 -target 6 src/de/tobifleig/lxc/plaf/impl/GenericPCPlatform.java

echo "Packing jar..."
cd classes
echo "Main-Class: de.tobifleig.lxc.plaf.impl.GenericPCPlatform" > manifest.txt
jar -cmf manifest.txt ../lanxchange.jar de

cd ..
echo "Packing files"
zip -r lxc.zip COPYING font_license.txt img/*.png lanxchange.jar lxc lxc.exe lxc_updates.pub Ubuntu-R.ttf

echo "Copying zip to repository..."
cp lxc.zip $DIR/releases/stable

echo "Done. Copied result to releases/stable. Unpack anywhere to install."
