#!/bin/bash

# This script compiles, packs, signs and publishes lxc (via automatic updates)

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo "Checking versions..."
# Read version numbers
newversion=$(grep -E 'public static final int versionId = [0-9]+;' src/de/tobifleig/lxc/LXC.java | grep -Eo [0-9]+)
oldversion=$(head -n 1 < update/v)
if [ $oldversion -ge $newversion ]; then
	echo "ERROR: version number must be greater than the current version!"
	exit 1
fi
oldtext=$(sed -n '2p' update/v)
echo "Old description for version $oldversion is: $oldtext"
read -p "Enter new description: " text

echo "Setting up build environment..."
if [ -e "/tmp/lxcbuild" ]; then
	rm -fr "/tmp/lxcbuild"
fi
mkdir "/tmp/lxcbuild"
mkdir "/tmp/lxcbuild/classes"

echo "Copying files to build dir..."
cp -r * "/tmp/lxcbuild"

echo "Compiling..."
cd "/tmp/lxcbuild"
javac -encoding utf8 -d classes -sourcepath src -source 6 -target 6 src/de/tobifleig/lxc/LXC.java

echo "Packing jar..."
cd classes
echo "Main-Class: de.tobifleig.lxc.LXC" > manifest.txt
jar -cmf manifest.txt ../lanxchange.jar de

cd ..
echo "Packing update..."
zip -r lxc.zip COPYING font_license.txt img/*.png lanxchange.jar lxc lxc.exe lxc_updates.pub Ubuntu-R.ttf

echo "Signing update..."
read -p "Please make sure the signing environment is found in /media/truecrypt1, then press enter to continue..."
echo "Setting up signing environment..."
if [ -e "/media/truecrypt1/lxc.zip" ]; then
	rm "/media/truecrypt1/lxc.zip"
fi
if [ -e "/media/truecrypt1/update_master.zip" ]; then
	rm "/media/truecrypt1/update_master.zip"
fi
if [ -e "/media/truecrypt1/lxc.sign" ]; then
	rm "/media/truecrypt1/lxc.sign"
fi
echo "Copying update into signing environment..."
cp "lxc.zip" "/media/truecrypt1/lxc.zip"
echo "Signing zip..."
cd "/media/truecrypt1"
java de.tobifleig.lxc.Signer
echo "Packing update master file..."
zip update_master.zip lxc.zip lxc.sign

echo "Copying update master zip to repository..."
cp update_master.zip $DIR/update

echo "Writing update version file..."
cd $DIR
echo $newversion > update/v
echo $text >> update/v

echo "Done. Commit and push directory update to apply."
